// Flag quiz data — country code + country names in Hebrew and Arabic
export const FLAGS = [
  { code: 'il', he: 'ישראל', ar: 'إسرائيل' },
  { code: 'us', he: 'ארצות הברית', ar: 'الولايات المتحدة' },
  { code: 'gb', he: 'בריטניה', ar: 'المملكة المتحدة' },
  { code: 'fr', he: 'צרפת', ar: 'فرنسا' },
  { code: 'de', he: 'גרמניה', ar: 'ألمانيا' },
  { code: 'it', he: 'איטליה', ar: 'إيطاليا' },
  { code: 'es', he: 'ספרד', ar: 'إسبانيا' },
  { code: 'pt', he: 'פורטוגל', ar: 'البرتغال' },
  { code: 'nl', he: 'הולנד', ar: 'هولندا' },
  { code: 'be', he: 'בלגיה', ar: 'بلجيكا' },
  { code: 'ch', he: 'שוויץ', ar: 'سويسرا' },
  { code: 'at', he: 'אוסטריה', ar: 'النمسا' },
  { code: 'se', he: 'שוודיה', ar: 'السويد' },
  { code: 'no', he: 'נורווגיה', ar: 'النرويج' },
  { code: 'dk', he: 'דנמרק', ar: 'الدنمارك' },
  { code: 'fi', he: 'פינלנד', ar: 'فنلندا' },
  { code: 'pl', he: 'פולין', ar: 'بولندا' },
  { code: 'gr', he: 'יוון', ar: 'اليونان' },
  { code: 'tr', he: 'טורקיה', ar: 'تركيا' },
  { code: 'ru', he: 'רוסיה', ar: 'روسيا' },
  { code: 'cn', he: 'סין', ar: 'الصين' },
  { code: 'jp', he: 'יפן', ar: 'اليابان' },
  { code: 'kr', he: 'קוריאה הדרומית', ar: 'كوريا الجنوبية' },
  { code: 'in', he: 'הודו', ar: 'الهند' },
  { code: 'br', he: 'ברזיל', ar: 'البرازيل' },
  { code: 'ar', he: 'ארגנטינה', ar: 'الأرجنتين' },
  { code: 'mx', he: 'מקסיקו', ar: 'المكسيك' },
  { code: 'ca', he: 'קנדה', ar: 'كندا' },
  { code: 'au', he: 'אוסטרליה', ar: 'أستراليا' },
  { code: 'za', he: 'דרום אפריקה', ar: 'جنوب أفريقيا' },
  { code: 'eg', he: 'מצרים', ar: 'مصر' },
  { code: 'sa', he: 'ערב הסעודית', ar: 'المملكة العربية السعودية' },
  { code: 'jo', he: 'ירדן', ar: 'الأردن' },
  { code: 'lb', he: 'לבנון', ar: 'لبنان' },
  { code: 'ir', he: 'איראן', ar: 'إيران' },
  { code: 'iq', he: 'עיראק', ar: 'العراق' },
  { code: 'th', he: 'תאילנד', ar: 'تايلاند' },
  { code: 'vn', he: 'וייטנאם', ar: 'فيتنام' },
  { code: 'ph', he: 'פיליפינים', ar: 'الفلبين' },
  { code: 'ng', he: 'ניגריה', ar: 'نيجيريا' },
  // Europe
  { code: 'ua', he: 'אוקראינה', ar: 'أوكرانيا' },
  { code: 'ro', he: 'רומניה', ar: 'رومانيا' },
  { code: 'cz', he: 'צ׳כיה', ar: 'التشيك' },
  { code: 'sk', he: 'סלובקיה', ar: 'سلوفاكيا' },
  { code: 'hu', he: 'הונגריה', ar: 'المجر' },
  { code: 'hr', he: 'קרואטיה', ar: 'كرواتيا' },
  { code: 'rs', he: 'סרביה', ar: 'صربيا' },
  { code: 'bg', he: 'בולגריה', ar: 'بلغاريا' },
  { code: 'si', he: 'סלובניה', ar: 'سلوفينيا' },
  { code: 'lt', he: 'ליטא', ar: 'ليتوانيا' },
  { code: 'lv', he: 'לטביה', ar: 'لاتفيا' },
  { code: 'ee', he: 'אסטוניה', ar: 'إستونيا' },
  { code: 'by', he: 'בלארוס', ar: 'بيلاروسيا' },
  { code: 'md', he: 'מולדובה', ar: 'مولدوفا' },
  { code: 'al', he: 'אלבניה', ar: 'ألبانيا' },
  { code: 'mk', he: 'מקדוניה', ar: 'مقدونيا' },
  { code: 'me', he: 'מונטנגרו', ar: 'الجبل الأسود' },
  { code: 'ba', he: 'בוסניה והרצגובינה', ar: 'البوسنة والهرسك' },
  { code: 'ie', he: 'אירלנד', ar: 'أيرلندا' },
  { code: 'is', he: 'איסלנד', ar: 'آيسلندا' },
  { code: 'lu', he: 'לוקסמבורג', ar: 'لوكسمبورغ' },
  { code: 'mt', he: 'מלטה', ar: 'مالطا' },
  { code: 'cy', he: 'קפריסין', ar: 'قبرص' },
  // Americas
  { code: 'cl', he: 'צ׳ילה', ar: 'تشيلي' },
  { code: 'co', he: 'קולומביה', ar: 'كولومبيا' },
  { code: 'pe', he: 'פרו', ar: 'بيرو' },
  { code: 've', he: 'ונצואלה', ar: 'فنزويلا' },
  { code: 'ec', he: 'אקוודור', ar: 'الإكوادور' },
  { code: 'bo', he: 'בוליביה', ar: 'بوليفيا' },
  { code: 'py', he: 'פרגוואי', ar: 'باراغواي' },
  { code: 'uy', he: 'אורוגוואי', ar: 'أوروغواي' },
  { code: 'cu', he: 'קובה', ar: 'كوبا' },
  { code: 'do', he: 'הרפובליקה הדומיניקנית', ar: 'جمهورية الدومينيكان' },
  { code: 'gt', he: 'גואטמלה', ar: 'غواتيمالا' },
  { code: 'hn', he: 'הונדורס', ar: 'هندوراس' },
  { code: 'cr', he: 'קוסטה ריקה', ar: 'كوستاريكا' },
  { code: 'pa', he: 'פנמה', ar: 'بنما' },
  { code: 'jm', he: 'ג׳מייקה', ar: 'جامايكا' },
  // Asia
  { code: 'id', he: 'אינדונזיה', ar: 'إندونيسيا' },
  { code: 'my', he: 'מלזיה', ar: 'ماليزيا' },
  { code: 'sg', he: 'סינגפור', ar: 'سنغافورة' },
  { code: 'pk', he: 'פקיסטן', ar: 'باكستان' },
  { code: 'bd', he: 'בנגלדש', ar: 'بنغلاديش' },
  { code: 'lk', he: 'סרי לנקה', ar: 'سريلانكا' },
  { code: 'mm', he: 'מיאנמר', ar: 'ميانمار' },
  { code: 'kh', he: 'קמבודיה', ar: 'كمبوديا' },
  { code: 'np', he: 'נפאל', ar: 'نيبال' },
  { code: 'mn', he: 'מונגוליה', ar: 'منغوليا' },
  { code: 'kz', he: 'קזחסטן', ar: 'كازاخستان' },
  { code: 'uz', he: 'אוזבקיסטן', ar: 'أوزبكستان' },
  { code: 'az', he: 'אזרבייג׳ן', ar: 'أذربيجان' },
  { code: 'ge', he: 'גאורגיה', ar: 'جورجيا' },
  { code: 'am', he: 'ארמניה', ar: 'أرمينيا' },
  { code: 'sy', he: 'סוריה', ar: 'سوريا' },
  { code: 'ye', he: 'תימן', ar: 'اليمن' },
  { code: 'ae', he: 'איחוד האמירויות', ar: 'الإمارات العربية المتحدة' },
  { code: 'qa', he: 'קטאר', ar: 'قطر' },
  { code: 'kw', he: 'כווית', ar: 'الكويت' },
  { code: 'om', he: 'עומאן', ar: 'عُمان' },
  { code: 'bh', he: 'בחריין', ar: 'البحرين' },
  { code: 'af', he: 'אפגניסטן', ar: 'أفغانستان' },
  { code: 'tw', he: 'טייוואן', ar: 'تايوان' },
  // Africa
  { code: 'ma', he: 'מרוקו', ar: 'المغرب' },
  { code: 'dz', he: 'אלג׳יריה', ar: 'الجزائر' },
  { code: 'tn', he: 'תוניסיה', ar: 'تونس' },
  { code: 'ly', he: 'לוב', ar: 'ليبيا' },
  { code: 'sd', he: 'סודן', ar: 'السودان' },
  { code: 'et', he: 'אתיופיה', ar: 'إثيوبيا' },
  { code: 'ke', he: 'קניה', ar: 'كينيا' },
  { code: 'tz', he: 'טנזניה', ar: 'تنزانيا' },
  { code: 'gh', he: 'גאנה', ar: 'غانا' },
  { code: 'cm', he: 'קמרון', ar: 'الكاميرون' },
  { code: 'ci', he: 'חוף השנהב', ar: 'ساحل العاج' },
  { code: 'sn', he: 'סנגל', ar: 'السنغال' },
  { code: 'ao', he: 'אנגולה', ar: 'أنغولا' },
  { code: 'mz', he: 'מוזמביק', ar: 'موزمبيق' },
  { code: 'mg', he: 'מדגסקר', ar: 'مدغشقر' },
  { code: 'zw', he: 'זימבבואה', ar: 'زيمبابوي' },
  { code: 'zm', he: 'זמביה', ar: 'زامبيا' },
  { code: 'ug', he: 'אוגנדה', ar: 'أوغندا' },
  { code: 'rw', he: 'רואנדה', ar: 'رواندا' },
  { code: 'na', he: 'נמיביה', ar: 'ناميبيا' },
  // Oceania
  { code: 'nz', he: 'ניו זילנד', ar: 'نيوزيلندا' },
  { code: 'fj', he: 'פיג׳י', ar: 'فيجي' },
  { code: 'pg', he: 'פפואה גינאה החדשה', ar: 'بابوا غينيا الجديدة' },
];

export function getFlagUrl(code) {
  return `https://flagcdn.com/w160/${code}.png`;
}

export function getRandomQuestion(lang, usedFlags = []) {
  const available = FLAGS.filter(f => !usedFlags.includes(f.code));
  const pool = available.length >= 3 ? available : FLAGS;
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  const correct = shuffled[0];
  const wrongs = shuffled.slice(1, 3);
  const options = [correct, ...wrongs].sort(() => Math.random() - 0.5);
  return {
    flag: correct.code,
    answer: correct[lang],
    options: options.map(o => o[lang]),
  };
}